version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - app-network

  # Backend API server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network

  # Development version
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://backend-dev:3001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend-dev
    networks:
      - app-network
    profiles:
      - dev

  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge
